#!/bin/bash
#
#
# smoke_test_errors
#
# yes, similar to smoke_test_failed
#
#
# snag error TC names from a basicAutomation.log and rerun them
#
#	INFILE
#		env variable to nominate the basicAutomation.log file that containes the FAILED TC names
#
#
i_am=${0}
case X${i_am} in
    X/*)
	i_am_from=$(dirname ${i_am})
	i_am=$(basename ${i_am})
	;;
    *)
	
	i_am_from="`pwd`/$(dirname ${i_am})"
	i_am_from=$(cd ${i_am_from} ; pwd )
	i_am=$(basename ${i_am})
	;;
esac

INFILE=${INFILE:-../../logs/basicAutomation.log}

automation='automation.pl'

engine='engine_for_smoke_test'

badflag='no'

for item in ${i_am_from}/${engine} ${i_am_from}/${automation} ${INFILE} ; do
	if [ ! -f ${item} ] ; then
		echo ""
		echo ""
		echo "Unable to locate smoke test item ${item}."
		echo ""
		echo ""
		badflag='yes'
	fi
done

if [ "X$badflag" != "Xno" ] ; then
	exit 2
fi


export TERM=dumb

Failed_TCs=""

nominees=$(fgrep FAILED $INFILE | awk ' $1 == "XXXX" { print $2; next}' )
characters=$(echo $nominees | wc -c)
length=$(echo $nominees | wc -w)

if [ $length -eq 0 -a $characters -eq 1 ] ; then
	echo ""
	echo "No failed TCs found in '$INFILE'"
	echo ""
	exit 0
fi

export ACTIVE_LIST="${nominees}"


export SMOKE_TEST_NAME=${i_am}

cd ${i_am_from}
exec ./${engine}
