#!/bin/bash
#
#
#
# extract_cbs2_req_res_log
#
# Try to get an intelligent 'slice' of the cbs2_req_res.log file
#
#
# instead of:
#	1) reading the whole thing via vi[m](1)
#	2) reading the whole thing via less(1)
#	3) trying to do something with tail(1) and manually scrolling the screen...
#
#
#
INFILE=${INFILE:-./cbs2_req_res.log}
OUTFILE=${OUTFILE:-${HOME}/log/$(basename $INFILE)}

outdir=$(dirname $OUTFILE)

if [ ! -d $outdir ] ; then
	echo "Output directory of '$outdir' does not exist..."
	exit 2
fi

myUserNameis=$(who am i | cut -f1 -d' ')

echo ' '
echo 'Getting the beginning line count...'
beginLine=$(wc -l ${INFILE} | awk '{print $1}')

echo ' '
echo "I am '$myUserNameis' for lines in $INFILE beginning at $beginLine into $OUTFILE"
echo ' '
/bin/echo -e -n "Hit enter to continue> "
read getline
echo ' '
echo "Extracting lines starting at $beginLine from $INFILE to $OUTFILE"
echo ' '
sed -e "1,${beginLine}d" ${INFILE} > ${OUTFILE}
echo Lines Extracted: $(wc -l $OUTFILE)
