#!/bin/bash
#
#
# smoke_test_achid
#
#
# ACH, anyone???
#
#
i_am=${0}
case X${i_am} in
    X/*)
	i_am_from=$(dirname ${i_am})
	i_am=$(basename ${i_am})
	;;
    *)
	
	i_am_from="`pwd`/$(dirname ${i_am})"
	i_am_from=$(cd ${i_am_from} ; pwd )
	i_am=$(basename ${i_am})
	;;
esac

automation='automation.pl'

engine='engine_for_smoke_test'

badflag='no'

for item in ${engine} ${automation} ; do
	if [ ! -f ${i_am_from}/${item} ] ; then
		echo ""
		echo ""
		echo "Unable to locate smoke test engine ${item} in directory with ${i_am}."
		echo ""
		echo ""
		badflag='yes'
	fi
done

if [ "X$badflag" != "Xno" ] ; then
	exit 2
fi


export TERM=dumb

Failed_TCs=""

export ACTIVE_LIST="\
TC_CBS2_V1_GET_ACH_ID_ASTAT_FT
TC_CBS2_V1_GET_ACH_ID_FE
TC_CBS2_V1_GET_ACH_ID_FT
TC_CBS2_V1_GET_ACH_ID_NXFR_FT
TC_CBS2_V1_GLOBAL_CIS_USER_FT
TC_CBS2_V1_GLOBAL_HOST_PIN_FT
TC_CBS2_V1_GLOBAL_INVALID_FI_ID_FE
TC_CBS2_V1_GLOBAL_MISSING_REQUEST_ID_FE
TC_CBS2_V1_GLOBAL_NULL_LIVE_PASSWORD_FT
TC_CBS2_V1_GLOBAL_RC_ZERO_WITH_ERRMSG_FT
TC_CBS2_V1_GLOBAL_SECURITY_FILTER_FE
TC_CBS2_V2_GET_ACH_ID_ASTAT_FT
TC_CBS2_V2_GET_ACH_ID_FE
TC_CBS2_V2_GET_ACH_ID_FT
TC_CBS2_V2_GET_ACH_ID_NXFR_FT
TC_CBS2_V2_GLOBAL_CIS_USER_FT
TC_CBS2_V2_GLOBAL_HOST_PIN_FT
TC_CBS2_V2_GLOBAL_INVALID_FI_ID_FE
TC_CBS2_V2_GLOBAL_MISSING_REQUEST_ID_FE
TC_CBS2_V2_GLOBAL_NULL_LIVE_PASSWORD_FT
TC_CBS2_V2_GLOBAL_RC_ZERO_WITH_ERRMSG_FT
TC_CBS2_V2_GLOBAL_SECURITY_FILTER_FE
"


export SMOKE_TEST_NAME=${i_am}

cd ${i_am_from}
exec ./${engine}
