#!/usr/bin/perl -w

use strict;

#----------------------------------------------------------------------#
#Set initial and final processing dates
#----------------------------------------------------------------------#
my $t_initial                   = "20090514";

#----------------------------------------------------------------------#
#Set user to begin creating transactions with:
#----------------------------------------------------------------------#
my $tickticker                  = 3300001;

#----------------------------------------------------------------------#
#Srt user to stop creating transaction with:
#----------------------------------------------------------------------#
my $tickticker_sto              = 3300001;

#----------------------------------------------------------------------#
#Used to set the twice monthly frequency date values. t_frequency=3
#----------------------------------------------------------------------#
my $date1                       = "14";
my $date2                       = "30";

#----------------------------------------------------------------------#
#FREQ-NUM1th-OCCUR-OFTHE-NUM2-WEEKDY - not typically set. Not used in
# or supported in production
#----------------------------------------------------------------------#
my $num1a                       = "2";
my $num2a                       = "4";

#----------------------------------------------------------------------#
#FREQ-EVRY-NUM1-WKS-ON-NUM2-DY - Used to set bi-weekly frequency's
#t_frequency=4
#----------------------------------------------------------------------#
my $num1b                       = "4";
my $num2b                       = "4";

#----------------------------------------------------------------------#
#Set the total number of payments for each transaction created
#----------------------------------------------------------------------#
my $pmt_cnt                     = "1";

#----------------------------------------------------------------------#
#Toggle for Send final payment notification 0 = Off - 1 = On.
#----------------------------------------------------------------------#
my $send_final                  = "0";

#----------------------------------------------------------------------#
#Payment Option:
#	 0 = default, host system determines use of funds
#	 1 = multiple payment, TAMT is assumed to be a multiple of the payment due.
#	 2 = interest-only payment.
#	 3 = principal-only payment.
#	 4 = excess-payment to interest.
#	 5 = excess payment to principal.
#	 6 = escrow-only payment.
#	 7 = fees-only payment.
#----------------------------------------------------------------------#
my $pay_opt					="0";

#----------------------------------------------------------------------#
#Email address of where to send notifications
#For large batches use: testmail@qa.digitalinsight.com
#----------------------------------------------------------------------#
my $email_add                   = "srtqa1\@gmail.com";

###########################################################################
#Begin creating SRT Migration flat file - DO NOT EDIT BELOW
###########################################################################
my $t_final                     = $t_initial;
my $values_inc                  = 1;
my $values_ticker               = $tickticker;
my $values_sto                  = $tickticker_sto;

print "The Dictionary contains ".($tickticker_sto - 3300000)." entries.\n";
print "[VALUES]\n";

while ( $values_ticker <=  $values_sto)
{
	print "$values_inc = $values_ticker\n";
	$values_inc++;
	$values_ticker++;
	
}	
	print "\n\n";
	print "[TABLES]\n";
	
while ( $tickticker <=  $tickticker_sto)
{
	print "\n";
	print "_NAME_:$tickticker\n";
	print"SERVICE,TEST,A_XTX,ACTION,T_INITIAL,T_FINAL,T_PMTCOUNT,A_TPAYOPT,T_FREQUENCY,T_NUM1,T_NUM2,A_FUSR,A_FNUM,A_FTYP,A_TUSR,A_TNUM,A_TTYP,A_TAMT,A_TXTYP,A_TDESC,A_TPAYOPT,A_EMAIL,A_SUBJECT,A_MESSAGE,A_FAILURESUBJECT,A_FAILUREMESSAGE,T_MFINALSUBJECT,T_MFINALBODY,A_NOBALCHK,T_MSENDFINAL,PIN\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,$t_final,0,$pay_opt,0,0,0,$tickticker,2758248117,1,".($tickticker+1).",717550591,0,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Checking To XUSR Savings - 0 FREQ-ONCE-NXT-RUN,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Checking To XUSR Savings - 0 FREQ-ONCE-NXT-RUN,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Checking To XUSR Savings - 0 FREQ-ONCE-NXT-RUN,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,1,$date1,0,$tickticker,2758248117,1,".($tickticker+1).",717550591,0,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Checking To XUSR Savings - 1 FREQ-ONCE-MO-ON-DY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Checking To XUSR Savings - 1 FREQ-ONCE-MO-ON-DY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Checking To XUSR Savings - 1 FREQ-ONCE-MO-ON-DY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
#	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,2,$num1a,$num2a,$tickticker,2758248117,1,".($tickticker+1).",717550591,0,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Checking To XUSR Savings - 2 FREQ-NUM1th-OCCUR-OFTHE-NUM2-WEEKDY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Checking To XUSR Savings - 2 FREQ-NUM1th-OCCUR-OFTHE-NUM2-WEEKDY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Checking To XUSR Savings - 2 FREQ-NUM1th-OCCUR-OFTHE-NUM2-WEEKDY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,3,$date1,$date2,$tickticker,2758248117,1,".($tickticker+1).",717550591,0,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Checking To XUSR Savings - 3 FREQ-2-DATES/MO,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Checking To XUSR Savings - 3 FREQ-2-DATES/MO,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Checking To XUSR Savings - 3 FREQ-2-DATES/MO,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,4,$num1b,$num2b,$tickticker,2758248117,1,".($tickticker+1).",717550591,0,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Checking To XUSR Savings - 4 FREQ-EVRY-NUM1-WKS-ON-NUM2-DY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Checking To XUSR Savings - 4 FREQ-EVRY-NUM1-WKS-ON-NUM2-DY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Checking To XUSR Savings - 4 FREQ-EVRY-NUM1-WKS-ON-NUM2-DY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,5,0,0,$tickticker,2758248117,1,".($tickticker+1).",717550591,0,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Checking To XUSR Savings - 5 FREQ-ANNUAL-ON-T_INITIAL,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Checking To XUSR Savings - 5 FREQ-ANNUAL-ON-T_INITIAL,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Checking To XUSR Savings - 5 FREQ-ANNUAL-ON-T_INITIAL,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,6,0,0,$tickticker,2758248117,1,".($tickticker+1).",717550591,0,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Checking To XUSR Savings - 6 FREQ-DAILY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Checking To XUSR Savings - 6 FREQ-DAILY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Checking To XUSR Savings - 6 FREQ-DAILY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,7,2,3,$tickticker,2758248117,1,".($tickticker+1).",717550591,0,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Checking To XUSR Savings - 7 FREQ-BI-WEEKLY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Checking To XUSR Savings - 7 FREQ-BI-WEEKLY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Checking To XUSR Savings - 7 FREQ-BI-WEEKLY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,8,0,0,$tickticker,2758248117,1,".($tickticker+1).",717550591,0,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Checking To XUSR Savings - 8 FREQ-QUARTERLY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Checking To XUSR Savings - 8 FREQ-QUARTERLY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Checking To XUSR Savings - 8 FREQ-QUARTERLY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,9,0,0,$tickticker,2758248117,1,".($tickticker+1).",717550591,0,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Checking To XUSR Savings - 9 FREQ-SEMI-ANNUAL,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Checking To XUSR Savings - 9 FREQ-SEMI-ANNUAL,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Checking To XUSR Savings - 9 FREQ-SEMI-ANNUAL,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,$t_final,0,$pay_opt,0,0,0,$tickticker,2758248117,1,".($tickticker+1).",365179,64,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Checking To XUSR Credit Card - 0 FREQ-ONCE-NXT-RUN,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Checking To XUSR Credit Card - 0 FREQ-ONCE-NXT-RUN,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Checking To XUSR Credit Card - 0 FREQ-ONCE-NXT-RUN,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,1,$date1,0,$tickticker,2758248117,1,".($tickticker+1).",365179,64,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Checking To XUSR Credit Card - 1 FREQ-ONCE-MO-ON-DY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Checking To XUSR Credit Card - 1 FREQ-ONCE-MO-ON-DY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Checking To XUSR Credit Card - 1 FREQ-ONCE-MO-ON-DY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
#	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,2,$num1a,$num2a,$tickticker,2758248117,1,".($tickticker+1).",365179,64,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Checking To XUSR Credit Card - 2 FREQ-NUM1th-OCCUR-OFTHE-NUM2-WEEKDY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Checking To XUSR Credit Card - 2 FREQ-NUM1th-OCCUR-OFTHE-NUM2-WEEKDY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Checking To XUSR Credit Card - 2 FREQ-NUM1th-OCCUR-OFTHE-NUM2-WEEKDY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,3,$date1,$date2,$tickticker,2758248117,1,".($tickticker+1).",365179,64,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Checking To XUSR Credit Card - 3 FREQ-2-DATES/MO,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Checking To XUSR Credit Card - 3 FREQ-2-DATES/MO,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Checking To XUSR Credit Card - 3 FREQ-2-DATES/MO,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,4,$num1b,$num2b,$tickticker,2758248117,1,".($tickticker+1).",365179,64,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Checking To XUSR Credit Card - 4 FREQ-EVRY-NUM1-WKS-ON-NUM2-DY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Checking To XUSR Credit Card - 4 FREQ-EVRY-NUM1-WKS-ON-NUM2-DY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Checking To XUSR Credit Card - 4 FREQ-EVRY-NUM1-WKS-ON-NUM2-DY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,5,0,0,$tickticker,2758248117,1,".($tickticker+1).",365179,64,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Checking To XUSR Credit Card - 5 FREQ-ANNUAL-ON-T_INITIAL,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Checking To XUSR Credit Card - 5 FREQ-ANNUAL-ON-T_INITIAL,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Checking To XUSR Credit Card - 5 FREQ-ANNUAL-ON-T_INITIAL,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,6,0,0,$tickticker,2758248117,1,".($tickticker+1).",365179,64,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Checking To XUSR Credit Card - 6 FREQ-DAILY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Checking To XUSR Credit Card - 6 FREQ-DAILY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Checking To XUSR Credit Card - 6 FREQ-DAILY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,7,2,3,$tickticker,2758248117,1,".($tickticker+1).",365179,64,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Checking To XUSR Credit Card - 7 FREQ-BI-WEEKLY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Checking To XUSR Credit Card - 7 FREQ-BI-WEEKLY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Checking To XUSR Credit Card - 7 FREQ-BI-WEEKLY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,8,0,0,$tickticker,2758248117,1,".($tickticker+1).",365179,64,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Checking To XUSR Credit Card - 8 FREQ-QUARTERLY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Checking To XUSR Credit Card - 8 FREQ-QUARTERLY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Checking To XUSR Credit Card - 8 FREQ-QUARTERLY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,9,0,0,$tickticker,2758248117,1,".($tickticker+1).",365179,64,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Checking To XUSR Credit Card - 9 FREQ-SEMI-ANNUAL,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Checking To XUSR Credit Card - 9 FREQ-SEMI-ANNUAL,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Checking To XUSR Credit Card - 9 FREQ-SEMI-ANNUAL,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,$t_final,0,$pay_opt,0,0,0,$tickticker,2758248117,1,".($tickticker+1).",465855,16,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Checking To XUSR Investment - 0 FREQ-ONCE-NXT-RUN,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Checking To XUSR Investment - 0 FREQ-ONCE-NXT-RUN,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Checking To XUSR Investment - 0 FREQ-ONCE-NXT-RUN,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,1,$date1,0,$tickticker,2758248117,1,".($tickticker+1).",465855,16,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Checking To XUSR Investment - 1 FREQ-ONCE-MO-ON-DY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Checking To XUSR Investment - 1 FREQ-ONCE-MO-ON-DY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Checking To XUSR Investment - 1 FREQ-ONCE-MO-ON-DY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
#	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,2,$num1a,$num2a,$tickticker,2758248117,1,".($tickticker+1).",465855,16,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Checking To XUSR Investment - 2 FREQ-NUM1th-OCCUR-OFTHE-NUM2-WEEKDY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Checking To XUSR Investment - 2 FREQ-NUM1th-OCCUR-OFTHE-NUM2-WEEKDY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Checking To XUSR Investment - 2 FREQ-NUM1th-OCCUR-OFTHE-NUM2-WEEKDY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,3,$date1,$date2,$tickticker,2758248117,1,".($tickticker+1).",465855,16,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Checking To XUSR Investment - 3 FREQ-2-DATES/MO,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Checking To XUSR Investment - 3 FREQ-2-DATES/MO,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Checking To XUSR Investment - 3 FREQ-2-DATES/MO,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,4,$num1b,$num2b,$tickticker,2758248117,1,".($tickticker+1).",465855,16,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Checking To XUSR Investment - 4 FREQ-EVRY-NUM1-WKS-ON-NUM2-DY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Checking To XUSR Investment - 4 FREQ-EVRY-NUM1-WKS-ON-NUM2-DY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Checking To XUSR Investment - 4 FREQ-EVRY-NUM1-WKS-ON-NUM2-DY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,5,0,0,$tickticker,2758248117,1,".($tickticker+1).",465855,16,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Checking To XUSR Investment - 5 FREQ-ANNUAL-ON-T_INITIAL,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Checking To XUSR Investment - 5 FREQ-ANNUAL-ON-T_INITIAL,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Checking To XUSR Investment - 5 FREQ-ANNUAL-ON-T_INITIAL,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,6,0,0,$tickticker,2758248117,1,".($tickticker+1).",465855,16,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Checking To XUSR Investment - 6 FREQ-DAILY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Checking To XUSR Investment - 6 FREQ-DAILY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Checking To XUSR Investment - 6 FREQ-DAILY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,7,2,3,$tickticker,2758248117,1,".($tickticker+1).",465855,16,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Checking To XUSR Investment - 7 FREQ-BI-WEEKLY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Checking To XUSR Investment - 7 FREQ-BI-WEEKLY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Checking To XUSR Investment - 7 FREQ-BI-WEEKLY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,8,0,0,$tickticker,2758248117,1,".($tickticker+1).",465855,16,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Checking To XUSR Investment - 8 FREQ-QUARTERLY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Checking To XUSR Investment - 8 FREQ-QUARTERLY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Checking To XUSR Investment - 8 FREQ-QUARTERLY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,9,0,0,$tickticker,2758248117,1,".($tickticker+1).",465855,16,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Checking To XUSR Investment - 9 FREQ-SEMI-ANNUAL,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Checking To XUSR Investment - 9 FREQ-SEMI-ANNUAL,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Checking To XUSR Investment - 9 FREQ-SEMI-ANNUAL,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,$t_final,0,$pay_opt,0,0,0,$tickticker,365179,64,".($tickticker+1).",2758248117,1,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Checking - 0 FREQ-ONCE-NXT-RUN,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Checking - 0 FREQ-ONCE-NXT-RUN,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Checking - 0 FREQ-ONCE-NXT-RUN,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,1,$date1,0,$tickticker,365179,64,".($tickticker+1).",2758248117,1,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Checking - 1 FREQ-ONCE-MO-ON-DY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Checking - 1 FREQ-ONCE-MO-ON-DY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Checking - 1 FREQ-ONCE-MO-ON-DY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
#	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,2,$num1a,$num2a,$tickticker,365179,64,".($tickticker+1).",2758248117,1,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Checking - 2 FREQ-NUM1th-OCCUR-OFTHE-NUM2-WEEKDY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Checking - 2 FREQ-NUM1th-OCCUR-OFTHE-NUM2-WEEKDY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Checking - 2 FREQ-NUM1th-OCCUR-OFTHE-NUM2-WEEKDY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,3,$date1,$date2,$tickticker,365179,64,".($tickticker+1).",2758248117,1,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Checking - 3 FREQ-2-DATES/MO,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Checking - 3 FREQ-2-DATES/MO,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Checking - 3 FREQ-2-DATES/MO,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,4,$num1b,$num2b,$tickticker,365179,64,".($tickticker+1).",2758248117,1,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Checking - 4 FREQ-EVRY-NUM1-WKS-ON-NUM2-DY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Checking - 4 FREQ-EVRY-NUM1-WKS-ON-NUM2-DY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Checking - 4 FREQ-EVRY-NUM1-WKS-ON-NUM2-DY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,5,0,0,$tickticker,365179,64,".($tickticker+1).",2758248117,1,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Checking - 5 FREQ-ANNUAL-ON-T_INITIAL,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Checking - 5 FREQ-ANNUAL-ON-T_INITIAL,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Checking - 5 FREQ-ANNUAL-ON-T_INITIAL,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,6,0,0,$tickticker,365179,64,".($tickticker+1).",2758248117,1,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Checking - 6 FREQ-DAILY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Checking - 6 FREQ-DAILY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Checking - 6 FREQ-DAILY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,7,2,3,$tickticker,365179,64,".($tickticker+1).",2758248117,1,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Checking - 7 FREQ-BI-WEEKLY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Checking - 7 FREQ-BI-WEEKLY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Checking - 7 FREQ-BI-WEEKLY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,8,0,0,$tickticker,365179,64,".($tickticker+1).",2758248117,1,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Checking - 8 FREQ-QUARTERLY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Checking - 8 FREQ-QUARTERLY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Checking - 8 FREQ-QUARTERLY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,9,0,0,$tickticker,365179,64,".($tickticker+1).",2758248117,1,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Checking - 9 FREQ-SEMI-ANNUAL,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Checking - 9 FREQ-SEMI-ANNUAL,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Checking - 9 FREQ-SEMI-ANNUAL,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,$t_final,0,$pay_opt,0,0,0,$tickticker,365179,64,".($tickticker+1).",365179,64,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Credit Card - 0 FREQ-ONCE-NXT-RUN,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Credit Card - 0 FREQ-ONCE-NXT-RUN,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Credit Card - 0 FREQ-ONCE-NXT-RUN,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,1,$date1,0,$tickticker,365179,64,".($tickticker+1).",365179,64,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Credit Card - 1 FREQ-ONCE-MO-ON-DY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Credit Card - 1 FREQ-ONCE-MO-ON-DY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Credit Card - 1 FREQ-ONCE-MO-ON-DY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
#	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,2,$num1a,$num2a,$tickticker,365179,64,".($tickticker+1).",365179,64,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Credit Card - 2 FREQ-NUM1th-OCCUR-OFTHE-NUM2-WEEKDY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Credit Card - 2 FREQ-NUM1th-OCCUR-OFTHE-NUM2-WEEKDY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Credit Card - 2 FREQ-NUM1th-OCCUR-OFTHE-NUM2-WEEKDY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,3,$date1,$date2,$tickticker,365179,64,".($tickticker+1).",365179,64,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Credit Card - 3 FREQ-2-DATES/MO,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Credit Card - 3 FREQ-2-DATES/MO,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Credit Card - 3 FREQ-2-DATES/MO,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,4,$num1b,$num2b,$tickticker,365179,64,".($tickticker+1).",365179,64,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Credit Card - 4 FREQ-EVRY-NUM1-WKS-ON-NUM2-DY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Credit Card - 4 FREQ-EVRY-NUM1-WKS-ON-NUM2-DY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Credit Card - 4 FREQ-EVRY-NUM1-WKS-ON-NUM2-DY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,5,0,0,$tickticker,365179,64,".($tickticker+1).",365179,64,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Credit Card - 5 FREQ-ANNUAL-ON-T_INITIAL,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Credit Card - 5 FREQ-ANNUAL-ON-T_INITIAL,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Credit Card - 5 FREQ-ANNUAL-ON-T_INITIAL,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,6,0,0,$tickticker,365179,64,".($tickticker+1).",365179,64,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Credit Card - 6 FREQ-DAILY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Credit Card - 6 FREQ-DAILY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Credit Card - 6 FREQ-DAILY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,7,2,3,$tickticker,365179,64,".($tickticker+1).",365179,64,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Credit Card - 7 FREQ-BI-WEEKLY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Credit Card - 7 FREQ-BI-WEEKLY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Credit Card - 7 FREQ-BI-WEEKLY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,8,0,0,$tickticker,365179,64,".($tickticker+1).",365179,64,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Credit Card - 8 FREQ-QUARTERLY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Credit Card - 8 FREQ-QUARTERLY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Credit Card - 8 FREQ-QUARTERLY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,9,0,0,$tickticker,365179,64,".($tickticker+1).",365179,64,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Credit Card - 9 FREQ-SEMI-ANNUAL,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Credit Card - 9 FREQ-SEMI-ANNUAL,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Credit Card - 9 FREQ-SEMI-ANNUAL,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,$t_final,0,$pay_opt,0,0,0,$tickticker,365179,64,".($tickticker+1).",365077,32,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Loan - 0 FREQ-ONCE-NXT-RUN,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Loan - 0 FREQ-ONCE-NXT-RUN,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Loan - 0 FREQ-ONCE-NXT-RUN,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,1,$date1,0,$tickticker,365179,64,".($tickticker+1).",365077,32,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Loan - 1 FREQ-ONCE-MO-ON-DY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Loan - 1 FREQ-ONCE-MO-ON-DY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Loan - 1 FREQ-ONCE-MO-ON-DY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
#	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,2,$num1a,$num2a,$tickticker,365179,64,".($tickticker+1).",365077,32,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Loan - 2 FREQ-NUM1th-OCCUR-OFTHE-NUM2-WEEKDY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Loan - 2 FREQ-NUM1th-OCCUR-OFTHE-NUM2-WEEKDY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Loan - 2 FREQ-NUM1th-OCCUR-OFTHE-NUM2-WEEKDY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,3,$date1,$date2,$tickticker,365179,64,".($tickticker+1).",365077,32,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Loan - 3 FREQ-2-DATES/MO,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Loan - 3 FREQ-2-DATES/MO,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Loan - 3 FREQ-2-DATES/MO,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,4,$num1b,$num2b,$tickticker,365179,64,".($tickticker+1).",365077,32,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Loan - 4 FREQ-EVRY-NUM1-WKS-ON-NUM2-DY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Loan - 4 FREQ-EVRY-NUM1-WKS-ON-NUM2-DY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Loan - 4 FREQ-EVRY-NUM1-WKS-ON-NUM2-DY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,5,0,0,$tickticker,365179,64,".($tickticker+1).",365077,32,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Loan - 5 FREQ-ANNUAL-ON-T_INITIAL,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Loan - 5 FREQ-ANNUAL-ON-T_INITIAL,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Loan - 5 FREQ-ANNUAL-ON-T_INITIAL,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,6,0,0,$tickticker,365179,64,".($tickticker+1).",365077,32,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Loan - 6 FREQ-DAILY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Loan - 6 FREQ-DAILY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Loan - 6 FREQ-DAILY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,7,2,3,$tickticker,365179,64,".($tickticker+1).",365077,32,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Loan - 7 FREQ-BI-WEEKLY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Loan - 7 FREQ-BI-WEEKLY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Loan - 7 FREQ-BI-WEEKLY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,8,0,0,$tickticker,365179,64,".($tickticker+1).",365077,32,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Loan - 8 FREQ-QUARTERLY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Loan - 8 FREQ-QUARTERLY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Loan - 8 FREQ-QUARTERLY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,9,0,0,$tickticker,365179,64,".($tickticker+1).",365077,32,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Loan - 9 FREQ-SEMI-ANNUAL,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Loan - 9 FREQ-SEMI-ANNUAL,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Loan - 9 FREQ-SEMI-ANNUAL,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,$t_final,0,$pay_opt,0,0,0,$tickticker,365179,64,".($tickticker+1).",465855,16,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Investment - 0 FREQ-ONCE-NXT-RUN,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Investment - 0 FREQ-ONCE-NXT-RUN,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Investment - 0 FREQ-ONCE-NXT-RUN,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,1,$date1,0,$tickticker,365179,64,".($tickticker+1).",465855,16,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Investment - 1 FREQ-ONCE-MO-ON-DY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Investment - 1 FREQ-ONCE-MO-ON-DY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Investment - 1 FREQ-ONCE-MO-ON-DY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
#	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,2,$num1a,$num2a,$tickticker,365179,64,".($tickticker+1).",465855,16,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Investment - 2 FREQ-NUM1th-OCCUR-OFTHE-NUM2-WEEKDY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Investment - 2 FREQ-NUM1th-OCCUR-OFTHE-NUM2-WEEKDY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Investment - 2 FREQ-NUM1th-OCCUR-OFTHE-NUM2-WEEKDY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,3,$date1,$date2,$tickticker,365179,64,".($tickticker+1).",465855,16,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Investment - 3 FREQ-2-DATES/MO,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Investment - 3 FREQ-2-DATES/MO,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Investment - 3 FREQ-2-DATES/MO,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,4,$num1b,$num2b,$tickticker,365179,64,".($tickticker+1).",465855,16,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Investment - 4 FREQ-EVRY-NUM1-WKS-ON-NUM2-DY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Investment - 4 FREQ-EVRY-NUM1-WKS-ON-NUM2-DY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Investment - 4 FREQ-EVRY-NUM1-WKS-ON-NUM2-DY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,5,0,0,$tickticker,365179,64,".($tickticker+1).",465855,16,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Investment - 5 FREQ-ANNUAL-ON-T_INITIAL,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Investment - 5 FREQ-ANNUAL-ON-T_INITIAL,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Investment - 5 FREQ-ANNUAL-ON-T_INITIAL,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,6,0,0,$tickticker,365179,64,".($tickticker+1).",465855,16,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Investment - 6 FREQ-DAILY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Investment - 6 FREQ-DAILY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Investment - 6 FREQ-DAILY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,7,2,3,$tickticker,365179,64,".($tickticker+1).",465855,16,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Investment - 7 FREQ-BI-WEEKLY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Investment - 7 FREQ-BI-WEEKLY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Investment - 7 FREQ-BI-WEEKLY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,8,0,0,$tickticker,365179,64,".($tickticker+1).",465855,16,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Investment - 8 FREQ-QUARTERLY,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Investment - 8 FREQ-QUARTERLY,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Investment - 8 FREQ-QUARTERLY,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	print"0,SCHEDULEDITEM,2,TRANSFER,$t_initial,,$pmt_cnt,$pay_opt,9,0,0,$tickticker,365179,64,".($tickticker+1).",465855,16,4500,0,SCHEDULEDTRANSFER,0,$email_add,SRT Subject - Credit Card To XUSR Investment - 9 FREQ-SEMI-ANNUAL,SRT Success Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRT Failure Subject - Credit Card To XUSR Investment - 9 FREQ-SEMI-ANNUAL,SRT Failure Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,SRTConcluded Scheduled Transfer Subject - Credit Card To XUSR Investment - 9 FREQ-SEMI-ANNUAL,SRT Final Transfer Message~nBreak~nBreak~m Double Break~mYou should not see user values here:(~n~a~u)~mFooter Text,0,$send_final,1234\n";
	
	$tickticker++;
}
